export const flattenBinaryTreeQuiz = [
    { question: 'What is the node order of the flattened binary tree?', options: ['Inorder', 'Preorder', 'Postorder', 'Level-order'], correctAnswer: 'Preorder', explanation: 'The binary tree is flattened such that the linked list nodes follow the preorder traversal of the original tree.' },
    { question: 'In the flattened binary tree, which pointer is used to link to the next node?', options: ['Left pointer', 'Right pointer', 'Parent pointer', 'Both left and right'], correctAnswer: 'Right pointer', explanation: 'After flattening, the left pointer of all nodes becomes NULL, and the right pointer points to the next node.' },
    { question: 'What is the optimal auxiliary space complexity to flatten a tree in-place without recursion?', options: ['O(n)', 'O(log n)', 'O(1)', 'O(h)'], correctAnswer: 'O(1)', explanation: 'Using the Morris traversal approach, we can flatten the tree in O(1) extra space.' },
    { question: 'What is the time complexity of the flattening algorithm?', options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(h)'], correctAnswer: 'O(n)', explanation: 'We visit each node a constant number of times (at most twice in Morris traversal), yielding O(n) time.' },
    { question: 'If a node has a left child, how does the Morris-style flattening relocate the right child?', options: ['It discards the right child', 'It appends the right child to the rightmost node of the left child', 'It makes the right child the left child', 'It swaps left and right children'], correctAnswer: 'It appends the right child to the rightmost node of the left child', explanation: 'The left subtree comes before the right subtree in preorder, so the right subtree must be attached to the rightmost node of the left subtree.' },
    { question: 'What is the left child of any node in a flattened binary tree?', options: ['NULL', 'The next node', 'The parent node', 'The previous node'], correctAnswer: 'NULL', explanation: 'In a flattened tree, all left pointers are set to NULL.' },
    { question: 'Which traversal can be used recursively to flatten a tree from right to left?', options: ['Root-Left-Right', 'Right-Left-Root', 'Left-Right-Root', 'Left-Root-Right'], correctAnswer: 'Right-Left-Root', explanation: 'Traversing Right, then Left, then Root allows us to update the right pointer of each node to point to the previously flattened node.' },
    { question: 'Which data structure can be used to flatten the tree iteratively (non-Morris)?', options: ['Queue', 'Stack', 'Heap', 'Graph'], correctAnswer: 'Stack', explanation: 'A Stack can store the nodes to simulate preorder traversal iteratively.' },
    { question: 'What happens to the leaf nodes of the original tree after flattening?', options: ['They are removed', 'They become inner nodes in the list', 'They remain leaf nodes', 'They are converted to NULL'], correctAnswer: 'They become inner nodes in the list', explanation: 'All nodes of the tree are preserved and chained sequentially into a single linked list.' },
    { question: 'What is the prerequisite for the flattening algorithm?', options: ['The tree must be a BST', 'The tree must be balanced', 'The tree must be a valid binary tree', 'The tree must be a complete tree'], correctAnswer: 'The tree must be a valid binary tree', explanation: 'Any valid binary tree can be flattened to a linked list.' }
  ];
