export const radixSortQuiz = [
  { question: 'What is the main idea behind Radix Sort?',options: ['Compare elements pairwise', 'Sort elements by individual digits', 'Use divide and conquer', 'Use a heap structure'],correctAnswer: 'Sort elements by individual digits',explanation: 'Radix Sort processes digits from least significant to most significant (or vice versa) to sort numbers.'},
  { question: 'Radix Sort is most efficient when the number of digits is:',options: ['Very large', 'Moderate and fixed', 'Unknown', 'Zero'],correctAnswer: 'Moderate and fixed',explanation: 'Radix Sort works well when the digit length is bounded and relatively small compared to the number of items.'},
  { question: 'Which stable sorting algorithm is commonly used as a subroutine in Radix Sort?',options: ['Quick Sort', 'Merge Sort', 'Counting Sort', 'Heap Sort'],correctAnswer: 'Counting Sort',explanation: 'Counting Sort is stable and ideal for sorting digits within each pass of Radix Sort.' },
  { question: 'What is the time complexity of Radix Sort for n numbers with d digits?',options: ['O(n log n)', 'O(n²)', 'O(d × (n + k))', 'O(n + d)'],correctAnswer: 'O(d × (n + k))',explanation: 'Radix Sort performs d passes and each pass can use Counting Sort in O(n + k) time.'},
  { question: 'Radix Sort is not a comparison-based sorting algorithm because it:',options: ['Uses swaps', 'Uses digit positions instead of comparisons', 'Uses recursion', 'Uses random pivot selection'],correctAnswer: 'Uses digit positions instead of comparisons',explanation: 'Radix Sort sorts by examining digit values rather than comparing whole elements directly.'},
  { question: 'For Radix Sort, what does "k" usually represent in complexity analysis?',options: ['Number of comparisons', 'Range of digit values', 'Number of swaps', 'Number of recursive calls'],correctAnswer: 'Range of digit values',explanation: 'k is the range of possible digit values, such as 10 for decimal digits.'},
  { question: 'When using LSD Radix Sort, sorting starts from:',options: ['Most significant digit', 'Least significant digit', 'Middle digit', 'Random digit'],correctAnswer: 'Least significant digit',explanation: 'LSD Radix Sort begins with the least significant digit and moves toward the most significant digit.' },
  { question: 'Radix Sort is particularly suited for sorting:',options: ['Floating-point numbers only', 'Strings only', 'Integers with fixed digit length', 'Unsorted graphs'],correctAnswer: 'Integers with fixed digit length',explanation: 'Radix Sort performs best on fixed-length integers or keys that can be processed digit by digit.'},
  { question: 'Which property must the digit-wise subroutine have for Radix Sort to work correctly?',options: ['Be unstable', 'Be stable', 'Use divide and conquer', 'Use randomness'],correctAnswer: 'Be stable',explanation: 'The digit-wise sort must be stable to preserve the order of equal digit values across passes.'},
  { question: 'What is a disadvantage of Radix Sort compared to comparison-based sorts?',options: ['Cannot sort integers', 'Requires additional space and digit-specific passes', 'Always slower', 'Depends on randomization'],correctAnswer: 'Requires additional space and digit-specific passes',explanation: 'Radix Sort can use extra memory for counting or buckets and needs multiple passes over the data.'}
];