export const longestCommonSubsequenceQuiz = [
    { question: 'What does the LCS of "ABCDGH" and "AEDFHR" equal to?', options: ['ADH', 'ADH', 'ADG', 'AED'], correctAnswer: 'ADH', explanation: 'The common subsequence is A, D, H with length 3.' },
    { question: 'What is the time complexity of the standard DP solution for LCS of two strings of size m and n?', options: ['O(m+n)', 'O(m*n)', 'O(2^(m+n))', 'O(m log n)'], correctAnswer: 'O(m*n)', explanation: 'We fill a 2D grid of size (m+1) x (n+1) which takes O(m*n) time.' },
    { question: 'What is the space complexity of standard LCS DP?', options: ['O(1)', 'O(m+n)', 'O(m*n)', 'O(2^(m+n))'], correctAnswer: 'O(m*n)', explanation: 'Standard DP uses a 2D table of size (m+1) x (n+1).' },
    { question: 'How do you transition when S1[i-1] == S2[j-1]?', options: ['dp[i][j] = dp[i-1][j-1] + 1', 'dp[i][j] = max(dp[i-1][j], dp[i][j-1])', 'dp[i][j] = dp[i-1][j] + 1', 'dp[i][j] = dp[i-1][j-1] + 1'], correctAnswer: 'dp[i][j] = dp[i-1][j-1] + 1', explanation: 'If characters match, we add 1 to the result of matching prefixes excluding these characters.' },
    { question: 'How do you transition when S1[i-1] != S2[j-1]?', options: ['dp[i][j] = dp[i-1][j-1] + 1', 'dp[i][j] = max(dp[i-1][j], dp[i][j-1])', 'dp[i][j] = min(dp[i-1][j], dp[i][j-1])', 'dp[i][j] = dp[i-1][j-1]'], correctAnswer: 'dp[i][j] = max(dp[i-1][j], dp[i][j-1])', explanation: 'When characters do not match, we take the maximum result of excluding one character from either string.' },
    { question: 'What is the optimized space complexity of LCS if only the length is required?', options: ['O(min(m, n))', 'O(1)', 'O(m*n)', 'O(m)'], correctAnswer: 'O(min(m, n))', explanation: 'We only need the current and previous rows of the DP table, reducing space to 2 * min(m, n).' },
    { question: 'In LCS reconstruction (backtracking), if dp[i][j] == dp[i-1][j], which way do we move?', options: ['Diagonally up-left', 'Up', 'Left', 'Right'], correctAnswer: 'Up', explanation: 'If dp[i][j] is equal to dp[i-1][j], it means the character S1[i-1] did not contribute to the LCS, so we move up.' },
    { question: 'Which programming paradigm is typically used to solve the LCS problem optimally?', options: ['Greedy', 'Divide and conquer', 'Dynamic programming', 'Backtracking'], correctAnswer: 'Dynamic programming', explanation: 'LCS has overlapping subproblems and optimal substructure, making it ideal for Dynamic Programming.' },
    { question: 'What is the LCS length between "abc" and "def"?', options: ['0', '1', '2', '3'], correctAnswer: '0', explanation: 'There are no common characters, so the LCS is empty (length 0).' },
    { question: 'Can LCS be used to find the Longest Palindromic Subsequence (LPS)?', options: ['No', 'Yes, by finding LCS of the string and its reverse', 'Yes, by sorting the string first', 'Yes, using LCS with itself'], correctAnswer: 'Yes, by finding LCS of the string and its reverse', explanation: 'LPS of a string S is equal to LCS(S, reverse(S)).' }
  ];
