export const aStarPathfindingQuiz = [
    { question: 'What is the evaluation function f(n) in A*?', options: ['g(n) - h(n)', 'g(n) + h(n)', 'g(n) * h(n)', 'h(n)'], correctAnswer: 'g(n) + h(n)', explanation: 'f(n) is the sum of path cost g(n) and heuristic estimate h(n).' },
    { question: 'What does g(n) represent in A*?', options: ['Estimated cost to goal', 'Actual cost from start to node n', 'Number of nodes expanded', 'The heuristic function'], correctAnswer: 'Actual cost from start to node n', explanation: 'g(n) represents the exact cost to reach node n from the start node.' },
    { question: 'What condition must a heuristic satisfy to guarantee A* finds the shortest path?', options: ['Must be dynamic', 'Must be admissible', 'Must be negative', 'Must overestimate the cost'], correctAnswer: 'Must be admissible', explanation: 'An admissible heuristic never overestimates the actual cost to reach the goal.' },
    { question: 'If h(n) is set to 0, what does A* behave like?', options: ['DFS', 'Dijkstra', 'Greedy Best-First Search', 'Bellman-Ford'], correctAnswer: 'Dijkstra', explanation: 'When h(n) = 0, f(n) = g(n), which is identical to Dijkstras algorithm.' },
    { question: 'If g(n) is set to 0, what does A* behave like?', options: ['Dijkstra', 'DFS', 'Greedy Best-First Search', 'BFS'], correctAnswer: 'Greedy Best-First Search', explanation: 'When g(n) = 0, f(n) = h(n), meaning A* only relies on the heuristic, making it Greedy Best-First Search.' },
    { question: 'Which data structure is typically used for the Open list in A*?', options: ['Stack', 'Queue', 'Priority Queue', 'BST'], correctAnswer: 'Priority Queue', explanation: 'A priority queue allows O(log n) retrieval of the node with the minimum f(n) value.' },
    { question: 'What is the Manhattan distance between points (1, 2) and (4, 6)?', options: ['5', '7', '10', '9'], correctAnswer: '7', explanation: 'Manhattan distance = |1-4| + |2-6| = 3 + 4 = 7.' },
    { question: 'What is the main disadvantage of A* compared to memory-optimized algorithms like IDA*?', options: ['High time complexity', 'High memory usage', 'Inability to find optimal path', 'Not suitable for grids'], correctAnswer: 'High memory usage', explanation: 'A* stores all visited and frontier nodes in memory, which can be extremely large.' },
    { question: 'What is a consistent heuristic?', options: ['A heuristic that is always positive', 'A heuristic where h(n) <= cost(n, c) + h(c)', 'A heuristic that always yields 0', 'A heuristic that matches g(n)'], correctAnswer: 'A heuristic where h(n) <= cost(n, c) + h(c)', explanation: 'A heuristic is consistent if its estimate is less than or equal to the cost of moving to a neighbor plus the neighbors estimate.' },
    { question: 'Can A* handle negative edge weights?', options: ['Yes, always', 'No, it can cause infinite loops or incorrect paths', 'Yes, if heuristic is negative', 'Yes, using scaling'], correctAnswer: 'No, it can cause infinite loops or incorrect paths', explanation: 'Like Dijkstra, A* assumes non-negative edge weights to guarantee efficiency and correctness.' }
  ];
