export const activitySelectionQuiz = [
  { question: 'What algorithmic paradigm is used for the Activity Selection problem?',options: ['Dynamic Programming', 'Greedy Algorithm', 'Backtracking', 'Divide and Conquer'],correctAnswer: 'Greedy Algorithm',explanation: 'Activity Selection chooses the next compatible activity with the earliest finish time, which is a greedy strategy.'},
  { question: 'What is the main objective of the Activity Selection problem?',options: ['Maximize total duration', 'Minimize number of activities', 'Select the maximum number of non-overlapping activities', 'Sort activities by start time'],correctAnswer: 'Select the maximum number of non-overlapping activities',explanation: 'The goal is to schedule as many compatible activities as possible without overlapping.'},
  { question: 'Which activity order is most useful for solving Activity Selection?',options: ['Sort by start time', 'Sort by duration', 'Sort by finish time', 'Random order'],correctAnswer: 'Sort by finish time',explanation: 'Selecting activities by earliest finish time yields an optimal greedy solution.'},
  { question: 'What is the key choice when selecting the next activity?',options: ['Choose the activity with the latest start', 'Choose the activity with the earliest finish that is compatible', 'Choose the longest activity', 'Choose the shortest activity'],correctAnswer: 'Choose the activity with the earliest finish that is compatible',explanation: 'The greedy choice is the next activity that finishes soonest and does not overlap the current schedule.'},
  { question: 'What condition must two selected activities satisfy?',options: ['Same start time', 'Overlapping intervals', 'One must start after the other finishes', 'Same finish time'],correctAnswer: 'One must start after the other finishes',explanation: 'Compatible activities cannot overlap, so the next one must begin after the previous one ends.'},
  { question: 'What is the time complexity of Activity Selection if activities are pre-sorted by finish time?',options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],correctAnswer: 'O(n)',explanation: 'Once sorted, selecting activities requires a single linear scan through the list.'},
  { question: 'If activities are not pre-sorted, what is the overall time complexity including sorting?',options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],correctAnswer: 'O(n log n)',explanation: 'Sorting activities by finish time dominates runtime, giving O(n log n) overall.'},
  { question: 'Which of these best describes the precondition for Activity Selection?',options: ['Activities must be sorted by start time', 'Each activity has a start and finish time', 'Activities must all be the same length', 'There must be only one activity'],correctAnswer: 'Each activity has a start and finish time',explanation: 'The problem requires each activity to have defined start and end times to determine compatibility.'},
  { question: 'What happens if you choose an activity that finishes later than another compatible one?',options: ['It always gives a better solution', 'It may reduce the total number of selected activities', 'It makes the algorithm stable', 'It has no effect'],correctAnswer: 'It may reduce the total number of selected activities',explanation: 'Choosing a later-finishing compatible activity can block more future choices and hurt optimality.'},
  { question: 'Which statement is true about the Activity Selection solution?',options: ['Greedy choice always leads to a globally optimal solution', 'It only finds a near-optimal solution', 'It must use recursion', 'It cannot handle more than 10 activities'],correctAnswer: 'Greedy choice always leads to a globally optimal solution',explanation: 'For Activity Selection, the earliest-finish greedy rule is proven to produce an optimal schedule.' }
];