export const quickSortQuiz = [
  { question: 'What algorithmic paradigm is Quick Sort based on?',options: ['Greedy Algorithm', 'Dynamic Programming', 'Divide and Conquer', 'Backtracking'],correctAnswer: 'Divide and Conquer',explanation: 'Quick Sort divides the array around a pivot, sorts subarrays recursively, and then combines results.'},
  { question: 'What is the average-case time complexity of Quick Sort?',options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],correctAnswer: 'O(n log n)',explanation: 'On average, Quick Sort partitions the array into balanced subarrays and sorts each in logarithmic depth.'},
  { question: 'What causes the worst-case time complexity of Quick Sort?',options: ['Balanced pivots', 'Choosing the median pivot', 'Already sorted or reverse-sorted input with poor pivot choice', 'Using counting sort'],correctAnswer: 'Already sorted or reverse-sorted input with poor pivot choice',explanation: 'If the pivot is always the smallest or largest element, Quick Sort degrades to O(n²).'},
  { question: 'Which step in Quick Sort rearranges elements around the pivot?',options: ['Merge', 'Partition', 'Selection', 'Heapify'],correctAnswer: 'Partition',explanation: 'Partitioning places elements less than pivot on one side and greater elements on the other.'},
  { question: 'Is Quick Sort stable by default?',options: ['Yes', 'No', 'Only for arrays', 'Only for linked lists'],correctAnswer: 'No',explanation: 'Quick Sort does not preserve the relative order of equal elements without modifications.'},
  { question: 'What is the space complexity of in-place Quick Sort?',options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],correctAnswer: 'O(log n)',explanation: 'In-place Quick Sort uses O(log n) stack space for recursion in the average case.'},
  { question: 'Which pivot selection method can improve Quick Sort performance?',options: ['First element only', 'Last element only', 'Median-of-three', 'Random placement'],correctAnswer: 'Median-of-three',explanation: 'Median-of-three pivot selection reduces the chance of poor partitions on sorted or nearly sorted input.'},
  { question: 'What condition indicates the base case of Quick Sort recursion?',options: ['The array is empty or has one element', 'The pivot is zero', 'All elements are equal', 'The array is sorted'],correctAnswer: 'The array is empty or has one element',explanation: 'A subarray of size 0 or 1 is already sorted and stops further recursion.' },
  { question: 'Quick Sort is generally preferred over Merge Sort because it:',options: ['Uses less average space', 'Is always stable', 'Uses no recursion', 'Has better worst-case time'],correctAnswer: 'Uses less average space',explanation: 'Quick Sort is often preferred because it is in-place and uses less extra memory than Merge Sort.'},
  { question: 'What is the primary advantage of using tail recursion optimization in Quick Sort?',options: ['Faster partitioning', 'Reduced recursion stack depth', 'Guaranteed stable sort', 'Better pivot selection'],correctAnswer: 'Reduced recursion stack depth',explanation: 'Tail recursion optimization converts one recursive call into iteration, lowering stack usage.'}
];