export const countingSortQuiz = [
  { question: 'What is the main idea behind Counting Sort?',options: ['Compare elements pairwise', 'Count occurrences of each value', 'Use recursive partitioning', 'Use a heap structure'],correctAnswer: 'Count occurrences of each value',explanation: 'Counting Sort tallies how many times each value appears and then reconstructs the sorted array.' },
  { question: 'Counting Sort is most efficient when the input values are:',options: ['Very large and sparse', 'Within a small integer range', 'Floating-point numbers', 'Already sorted'],correctAnswer: 'Within a small integer range',explanation: 'Counting Sort performs best when the values fit in a small range relative to the number of elements.'},
  { question: 'What is the time complexity of Counting Sort for n elements and range k?',options: ['O(n log n)', 'O(n + k)', 'O(n²)', 'O(k log n)'],correctAnswer: 'O(n + k)',explanation: 'Counting Sort runs in linear time plus the cost of processing the value range.'},
  { question: 'What must be true about the values for classical Counting Sort to work correctly?',options: ['They are all unique', 'They are integers', 'They are strings', 'They are negative only'],correctAnswer: 'They are integers',explanation: 'Counting Sort uses array indices based on values, so it requires integer keys.'},
  { question: 'What does the auxiliary array in Counting Sort store?',options: ['Sorted result directly', 'Cumulative counts of values', 'Pivot positions', 'Swapped indices'],correctAnswer: 'Cumulative counts of values',explanation: 'The count array is converted to cumulative counts to determine positions in the output.'},
  { question: 'Is Counting Sort stable?',options: ['Yes', 'No', 'Only if implemented with recursion', 'Only for distinct values'],correctAnswer: 'Yes',explanation: 'Counting Sort can be stable when values are placed into output in reverse order using cumulative counts.'},
  { question: 'What is the space complexity of Counting Sort?',options: ['O(1)', 'O(n + k)', 'O(n²)', 'O(log n)'],correctAnswer: 'O(n + k)',explanation: 'Counting Sort uses extra arrays for the counts and the output, so space is linear in n plus the range k.' },
  { question: 'Which step produces the final sorted output in Counting Sort?',options: ['Sorting the count array', 'Placing values based on cumulative counts', 'Swapping adjacent elements', 'Merging subarrays'],correctAnswer: 'Placing values based on cumulative counts',explanation: 'The algorithm places each input element into the correct output position using the count array.'},
  { question: 'What happens if the value range k is much larger than n?',options: ['Counting Sort remains optimal', 'Space and time usage become large', 'It becomes stable', 'It becomes comparison-based'],correctAnswer: 'Space and time usage become large',explanation: 'A large k causes extra overhead in the count array, making Counting Sort inefficient.'},
  { question: 'Counting Sort is often used as a subroutine in which other algorithm?',options: ['Quick Sort', 'Merge Sort', 'Radix Sort', 'Binary Search'],correctAnswer: 'Radix Sort',explanation: 'Radix Sort uses Counting Sort as a stable subroutine to sort by individual digits.'}
];