export const longestRepeatingQuiz = [
    { question: 'What technique is used to solve Longest Repeating Character Replacement optimally?', options: ['Dynamic Programming', 'Sliding Window', 'Backtracking', 'Greedy'], correctAnswer: 'Sliding Window', explanation: 'The sliding window technique maintains a window where at most k replacements are needed to make all characters the same.' },
    { question: 'What is the time complexity of the optimal solution?', options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(26n)'], correctAnswer: 'O(n)', explanation: 'Each character is visited at most twice — once by the right pointer and once by the left pointer.' },
    { question: 'What does "maxCount" represent in the algorithm?', options: ['Total characters in window', 'Number of replacements used', 'Frequency of the most common character in the window', 'Window size'], correctAnswer: 'Frequency of the most common character in the window', explanation: 'maxCount tracks the highest frequency of any single character in the current window.' },
    { question: 'What is the condition to shrink the window?', options: ['window_size > k', 'window_size - maxCount > k', 'maxCount > k', 'window_size == k'], correctAnswer: 'window_size - maxCount > k', explanation: 'window_size - maxCount gives the number of characters that need replacing. If it exceeds k, shrink the window.' },
    { question: 'What is the space complexity of the solution?', options: ['O(n)', 'O(26)', 'O(1)', 'O(k)'], correctAnswer: 'O(1)', explanation: 'Only a fixed-size array of 26 characters is used regardless of input size.' },
    { question: 'For s = "ABAB" and k = 2, what is the answer?', options: ['2', '3', '4', '5'], correctAnswer: '4', explanation: 'Replace 2 characters to make the whole string "AAAA" or "BBBB" — length 4.' },
    { question: 'For s = "AABABBA" and k = 1, what is the answer?', options: ['3', '4', '5', '6'], correctAnswer: '4', explanation: 'The longest window with at most 1 replacement is "AABA" or "ABBB" — length 4.' },
    { question: 'What happens to maxCount when the window shrinks?', options: ['It resets to 0', 'It decreases by 1', 'It stays the same or is not recalculated', 'It is recalculated from scratch'], correctAnswer: 'It stays the same or is not recalculated', explanation: 'maxCount is never decreased when shrinking — this is a key optimization that keeps the algorithm O(n).' },
    { question: 'Which pointer expands the window?', options: ['Left pointer', 'Right pointer', 'Both pointers', 'Middle pointer'], correctAnswer: 'Right pointer', explanation: 'The right pointer moves forward to expand the window, while the left pointer shrinks it when needed.' },
    { question: 'What character set does the standard version of this problem use?', options: ['Lowercase letters', 'Uppercase letters', 'Digits', 'All ASCII characters'], correctAnswer: 'Uppercase letters', explanation: 'The standard LeetCode version uses uppercase English letters A-Z.' },
];
