export const singleNumberQuiz = [
    { question: 'What is the result of A ⊕ A (XOR of a number with itself)?', options: ['A', '2A', '0', '1'], correctAnswer: '0', explanation: 'Any number XORed with itself is 0 because all bits match.' },
    { question: 'What is the result of A ⊕ 0?', options: ['0', 'A', '1', '-A'], correctAnswer: 'A', explanation: 'Any number XORed with 0 remains unchanged.' },
    { question: 'Which property allows us to XOR numbers in any order?', options: ['Distributive', 'Associative and Commutative', 'Idempotent', 'Transitive'], correctAnswer: 'Associative and Commutative', explanation: 'XOR is both commutative (A^B = B^A) and associative (A^(B^C) = (A^B)^C).' },
    { question: 'What is the time complexity of finding a single number in an array of size n using the XOR trick?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], correctAnswer: 'O(n)', explanation: 'We iterate through the array of size n exactly once.' },
    { question: 'What is the space complexity of the XOR trick?', options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], correctAnswer: 'O(1)', explanation: 'The XOR trick only uses a single variable to accumulate the XOR sum.' },
    { question: 'Under what condition does the basic XOR trick fail to find the unique element?', options: ['All duplicates appear exactly twice', 'Duplicates appear an odd number of times', 'The unique element appears twice', 'The array is unsorted'], correctAnswer: 'The unique element appears twice', explanation: 'If the unique element appears twice, it will cancel out to 0.' },
    { question: 'If an array has numbers [4, 1, 2, 1, 2], what is the cumulative XOR sum?', options: ['0', '1', '2', '4'], correctAnswer: '4', explanation: '1^1=0, 2^2=0, and 4^0=4.' },
    { question: 'Can the XOR trick be used to find two unique numbers in an array where others appear twice?', options: ['No, only one', 'Yes, by partitioning the array based on a set bit', 'Yes, by sorting first', 'Yes, using an extra array'], correctAnswer: 'Yes, by partitioning the array based on a set bit', explanation: 'XORing all elements gives A^B. We can find the lowest set bit in A^B and split the array into two groups to find both.' },
    { question: 'How is the XOR operator represented in C, C++, Java, and Python?', options: ['&', '|', '^', '~'], correctAnswer: '^', explanation: 'The caret (^) symbol represents bitwise XOR in these languages.' },
    { question: 'What is the binary XOR of 1010 and 1100?', options: ['1110', '0110', '0100', '1000'], correctAnswer: '0110', explanation: '1010 ^ 1100 = 0110 (only bits that are different become 1).' }
  ];
