export const editDistanceQuiz = [
  { question: 'What is the primary goal of the Edit Distance (Levenshtein Distance) algorithm?', options: ['Sort two strings', 'Find the minimum operations to convert one string into another', 'Find the longest substring', 'Reverse a string'], correctAnswer: 'Find the minimum operations to convert one string into another', explanation: 'Edit Distance computes the minimum number of insertions, deletions, and replacements needed to transform one string into another.' },
  { question: 'Which algorithmic technique is commonly used to solve the Edit Distance problem efficiently?', options: ['Greedy', 'Backtracking', 'Dynamic Programming', 'Divide and Conquer'], correctAnswer: 'Dynamic Programming', explanation: 'Edit Distance is efficiently solved using Dynamic Programming because it has overlapping subproblems and optimal substructure.' },
  { question: 'Which of the following operations is NOT allowed in the standard Levenshtein Distance?', options: ['Insertion', 'Deletion', 'Replacement', 'Swapping adjacent characters'], correctAnswer: 'Swapping adjacent characters', explanation: 'Standard Levenshtein Distance only allows insertion, deletion, and replacement. Swapping is allowed in Damerau-Levenshtein Distance.' },
  { question: 'What is the base value of dp[0][j] in the Edit Distance DP table?', options: ['0', 'j', '1', 'Infinity'], correctAnswer: 'j', explanation: 'Converting an empty string into a string of length j requires j insertions.' },
  { question: 'What is the base value of dp[i][0] in the Edit Distance DP table?', options: ['0', 'i', '1', 'Infinity'], correctAnswer: 'i', explanation: 'Converting a string of length i into an empty string requires i deletions.' },
  { question: 'What is the time complexity of the standard Dynamic Programming solution for Edit Distance?', options: ['O(n)', 'O(log n)', 'O(m × n)', 'O(n² log n)'], correctAnswer: 'O(m × n)', explanation: 'The DP table has m × n cells, and each cell is computed once.' },
  { question: 'What is the space complexity of the standard Edit Distance Dynamic Programming algorithm?', options: ['O(1)', 'O(m + n)', 'O(m × n)', 'O(log n)'], correctAnswer: 'O(m × n)', explanation: 'The standard solution stores an entire DP table of size (m + 1) × (n + 1).' },
  { question: 'What value is stored in dp[i][j]?', options: ['The longest common subsequence', 'The minimum edit distance between prefixes of the two strings', 'The number of matching characters', 'The ASCII difference between two characters'], correctAnswer: 'The minimum edit distance between prefixes of the two strings', explanation: 'Each DP cell stores the minimum operations required to convert the first i characters into the first j characters.' },
  { question: 'If the current characters of both strings are equal, how is dp[i][j] computed?', options: ['dp[i - 1][j] + 1', 'dp[i][j - 1] + 1', 'dp[i - 1][j - 1]', '1 + min(dp[i - 1][j], dp[i][j - 1])'], correctAnswer: 'dp[i - 1][j - 1]', explanation: 'When the characters match, no operation is required, so the diagonal value is copied.' },
  { question: 'Which recurrence relation is used when the current characters are different?', options: ['max(dp[i-1][j], dp[i][j-1])', '1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])', 'dp[i-1][j-1] + 2', 'dp[i][j] = i + j'], correctAnswer: '1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])', explanation: 'The minimum of deletion, insertion, and replacement costs is chosen, then one operation is added.' },
];