export const fractionalKnapsackQuiz = [
  { question: 'Which algorithmic technique is used in the Fractional Knapsack problem?', options: ['Dynamic Programming', 'Greedy', 'Backtracking', 'Divide and Conquer'], correctAnswer: 'Greedy', explanation: 'Fractional Knapsack follows the greedy approach by selecting items with the highest value-to-weight ratio first.' },
  { question: 'What is the key criterion for selecting items in Fractional Knapsack?', options: ['Highest weight', 'Lowest weight', 'Highest value', 'Highest value-to-weight ratio'], correctAnswer: 'Highest value-to-weight ratio', explanation: 'Items are selected based on maximum value obtained per unit weight.' },
  { question: 'Can items be divided in the Fractional Knapsack problem?', options: ['Yes', 'No', 'Only once', 'Only for expensive items'], correctAnswer: 'Yes', explanation: 'Items can be taken partially, which makes the greedy approach optimal.' },
  { question: 'What is the time complexity of Fractional Knapsack after sorting?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(n²)'], correctAnswer: 'O(n log n)', explanation: 'Sorting items by value-to-weight ratio takes O(n log n) time.' },
  { question: 'Why does the greedy approach work for Fractional Knapsack?', options: ['Items are sorted', 'Fractions of items can be taken', 'Weights are fixed', 'Values are unique'], correctAnswer: 'Fractions of items can be taken', explanation: 'Since fractions are allowed, choosing the best ratio item at each step always leads to an optimal solution.' },
  { question: 'Which of the following is NOT true about Fractional Knapsack?', options: ['Uses Greedy Strategy', 'Allows fractional items', 'Always gives optimal solution', 'Requires Dynamic Programming'], correctAnswer: 'Requires Dynamic Programming', explanation: 'Fractional Knapsack is solved optimally using a greedy approach, not dynamic programming.' },
  { question: 'What happens when the remaining capacity is less than the weight of the current item?', options: ['Skip the item', 'Take the whole item', 'Take a fraction of the item', 'End the process'], correctAnswer: 'Take a fraction of the item', explanation: 'The required fraction of the item is taken to fill the remaining capacity.' },
  { question: 'What is the value-to-weight ratio of an item with value 60 and weight 10?', options: ['5', '6', '10', '50'], correctAnswer: '6', explanation: 'Value-to-weight ratio = 60 / 10 = 6.' },
  { question: 'What is the space complexity of the standard Fractional Knapsack algorithm?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], correctAnswer: 'O(n)', explanation: 'Extra space is used to store and sort item information.' },
  { question: 'What is the major difference between Fractional Knapsack and 0/1 Knapsack?', options: ['Sorting method', 'Time complexity', 'Items can be taken partially', 'Number of items'], correctAnswer: 'Items can be taken partially', explanation: 'Fractional Knapsack allows taking fractions of items, while 0/1 Knapsack requires taking an item completely or not at all.' },
];