export const sudokuSolverQuiz = [
  { question: 'What is the worst-case time complexity of a backtracking Sudoku solver on a blank 9×9 grid?',options: ['O(n)', 'O(n²)', 'O(9^81)', 'O(log n)'],correctAnswer: 'O(9^81)',explanation: 'Each of the 81 cells may have up to 9 possibilities, giving an exponential upper bound of O(9^81).'},
  { question: 'Which checks are required before placing a digit in a Sudoku cell?',options: ['Row only', 'Column only', 'Row, column, and 3×3 subgrid', 'Row and diagonal'],correctAnswer: 'Row, column, and 3×3 subgrid',explanation: 'Sudoku rules require every digit to be unique in its row, its column, and its 3×3 box.'},
  { question: 'What does the solver do when a trial number leads to a dead end?',options: ['Keeps the number and continues', 'Resets the cell and backtracks', 'Terminates the algorithm', 'Skips the cell permanently'],correctAnswer: 'Resets the cell and backtracks',explanation: 'Backtracking removes the number and returns to a previous decision to try a different value.'},
  { question: 'How does the solver know the puzzle is solved?',options: ['When one row is filled', 'When there are no empty cells left', 'When recursion depth reaches 81', 'When all digits 1–9 appear in the first row'],correctAnswer: 'When there are no empty cells left',explanation: 'A valid Sudoku solution has all cells filled legally, so no empty cells remain.'},
  { question: 'What is a common representation for an empty Sudoku cell in code?',options: ['0', '-1', '9', '100'], correctAnswer: '0', explanation: 'Most Sudoku solver implementations use 0 to denote an empty cell that needs to be filled.' },
  { question: 'What type of traversal does recursive backtracking resemble?',options: ['Breadth-First Search', 'Depth-First Search', 'Dijkstra\'s Algorithm', 'Greedy Search'],correctAnswer: 'Depth-First Search', explanation: 'Backtracking explores each branch deeply before returning to try another branch, similar to DFS.' },
  { question: 'Which expression gives the starting row index of a 3×3 subgrid for a given row?',options: ['row / 3', 'row - (row % 3)', 'row + 3', '(row + 3) % 3'],correctAnswer: 'row - (row % 3)',explanation: 'Subtracting row % 3 yields the top-left row index of the current 3×3 box.' },
  { question: 'What causes solveSudoku to return false for an empty cell?',options: ['A valid number is placed', 'All digits 1–9 fail the safety check', 'The board is full', 'Grid size is not 9×9'],correctAnswer: 'All digits 1–9 fail the safety check',explanation: 'If no legal digit fits the current empty cell, the current path is invalid and backtracking occurs.'},
  { question: 'What is the main advantage of using backtracking for Sudoku?',options: ['Always finds the fastest solution', 'Guarantees a solution if one exists', 'Uses constant time', 'Does not require recursion'],correctAnswer: 'Guarantees a solution if one exists',explanation: 'Backtracking exhaustively searches valid combinations and will find a solvable board if a solution exists.'},
  { question: 'What is the worst-case time complexity of a backtracking Sudoku solver on a blank 9×9 grid?',options: ['O(n)', 'O(n²)', 'O(9^81)', 'O(log n)'],correctAnswer: 'O(9^81)',explanation: 'Each of the 81 cells may have up to 9 possibilities, giving an exponential upper bound of O(9^81).'}
];