export const huffmanCodingQuiz = [
    { question: 'What type of algorithm is Huffman Coding?', options: ['Dynamic Programming', 'Greedy', 'Backtracking', 'Divide and Conquer'], correctAnswer: 'Greedy', explanation: 'Huffman Coding is a greedy algorithm — it always merges the two nodes with the lowest frequency at each step.' },
    { question: 'What data structure is used to build the Huffman tree efficiently?', options: ['Stack', 'Queue', 'Min-Heap (Priority Queue)', 'Hash Map'], correctAnswer: 'Min-Heap (Priority Queue)', explanation: 'A min-heap allows efficient extraction of the two lowest-frequency nodes at each step in O(log n) time.' },
    { question: 'What is the time complexity of Huffman Coding?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2^n)'], correctAnswer: 'O(n log n)', explanation: 'Building the heap takes O(n) and each of the n-1 merge operations takes O(log n), giving O(n log n) total.' },
    { question: 'What property do Huffman codes have?', options: ['Fixed length', 'Prefix-free', 'Suffix-free', 'Equal frequency'], correctAnswer: 'Prefix-free', explanation: 'Huffman codes are prefix-free — no code is a prefix of another, which allows unambiguous decoding.' },
    { question: 'Which character gets the shortest Huffman code?', options: ['The least frequent character', 'The most frequent character', 'The first character alphabetically', 'The last character in input'], correctAnswer: 'The most frequent character', explanation: 'More frequent characters are placed closer to the root of the Huffman tree, resulting in shorter codes.' },
    { question: 'What does a left edge represent in a Huffman tree?', options: ['1', '0', 'Higher frequency', 'Lower frequency'], correctAnswer: '0', explanation: 'By convention, a left edge in the Huffman tree represents a 0 bit and a right edge represents a 1 bit.' },
    { question: 'What is the space complexity of Huffman Coding?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], correctAnswer: 'O(n)', explanation: 'The Huffman tree has at most 2n - 1 nodes for n unique characters, giving O(n) space complexity.' },
    { question: 'What is the minimum number of characters needed to apply Huffman Coding?', options: ['1', '2', '3', '4'], correctAnswer: '1', explanation: 'Huffman Coding can be applied to even a single character, which would be assigned the code "0".' },
    { question: 'What happens when two nodes have equal frequency during tree construction?', options: ['The algorithm fails', 'Either can be chosen — the result is still optimal', 'The alphabetically first is always chosen', 'The larger node is chosen'], correctAnswer: 'Either can be chosen — the result is still optimal', explanation: 'When frequencies are equal, either node can be chosen. Different choices may produce different but equally optimal trees.' },
    { question: 'What type of compression does Huffman Coding provide?', options: ['Lossy compression', 'Lossless compression', 'Partial compression', 'No compression'], correctAnswer: 'Lossless compression', explanation: 'Huffman Coding is lossless — the original data can be perfectly reconstructed from the encoded output.' },
];
