export const minimumWindowSubstringQuiz = [
    { question: 'What technique is used to solve Minimum Window Substring optimally?', options: ['Dynamic Programming', 'Sliding Window', 'Backtracking', 'Binary Search'], correctAnswer: 'Sliding Window', explanation: 'The sliding window technique expands the window to cover all characters of t, then shrinks it to find the minimum valid window.' },
    { question: 'What is the time complexity of the optimal solution?', options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(n * m)'], correctAnswer: 'O(n)', explanation: 'Each character in s is visited at most twice — once by the right pointer and once by the left pointer.' },
    { question: 'What does the "have" variable represent in the algorithm?', options: ['Total characters in window', 'Number of unique characters in t', 'Number of characters in t whose frequency is satisfied in the window', 'Window size'], correctAnswer: 'Number of characters in t whose frequency is satisfied in the window', explanation: '"have" counts how many unique characters from t have their required frequency met in the current window.' },
    { question: 'When do we shrink the window from the left?', options: ['When window size exceeds t length', 'When have == required', 'When a character is not in t', 'When right pointer reaches end'], correctAnswer: 'When have == required', explanation: 'Once all characters of t are satisfied (have == required), we shrink from the left to minimize the window.' },
    { question: 'What is the space complexity of the solution?', options: ['O(n)', 'O(m)', 'O(1)', 'O(k) where k is unique chars in s and t'], correctAnswer: 'O(k) where k is unique chars in s and t', explanation: 'Two frequency maps are used — one for t and one for the window — each bounded by the number of unique characters.' },
    { question: 'For s = "ADOBECODEBANC" and t = "ABC", what is the answer?', options: ['ADOBEC', 'BANC', 'DOBECODEBA', 'ABC'], correctAnswer: 'BANC', explanation: '"BANC" is the smallest substring of s containing all characters A, B, C.' },
    { question: 'What is returned if no valid window exists?', options: ['-1', 'null', 'Empty string ""', '0'], correctAnswer: 'Empty string ""', explanation: 'If no valid window is found, an empty string is returned as per the problem definition.' },
    { question: 'How is the "required" variable calculated?', options: ['Length of t', 'Number of unique characters in t', 'Length of s', 'Length of s minus length of t'], correctAnswer: 'Number of unique characters in t', explanation: '"required" is the count of unique characters in t that must be satisfied in the window.' },
    { question: 'Which pointer expands the window in Minimum Window Substring?', options: ['Left pointer', 'Right pointer', 'Both pointers', 'Middle pointer'], correctAnswer: 'Right pointer', explanation: 'The right pointer expands the window to include more characters, while the left pointer shrinks it.' },
    { question: 'What happens to the window frequency map when the left pointer moves?', options: ['It is cleared', 'The character at left is decremented', 'The character at left is removed', 'Nothing changes'], correctAnswer: 'The character at left is decremented', explanation: 'When the left pointer moves right, the frequency of the character leaving the window is decremented in the window map.' },
];
