export const wordSearchGridQuiz = [
  { question: 'Which algorithmic technique is used in the Word Search Grid problem?', options: ['Greedy', 'Dynamic Programming', 'Backtracking', 'Binary Search'], correctAnswer: 'Backtracking', explanation: 'Word Search uses DFS with backtracking to explore all possible paths in the grid.' },
  { question: 'In how many directions does the Word Search algorithm explore from each cell?', options: ['2', '3', '4', '8'], correctAnswer: '4', explanation: 'The algorithm explores up, down, left, and right — four directions from each cell.' },
  { question: 'Why is a cell temporarily marked during DFS in Word Search?', options: ['To count visits', 'To avoid revisiting the same cell in the current path', 'To mark the answer', 'To speed up search'], correctAnswer: 'To avoid revisiting the same cell in the current path', explanation: 'Marking prevents the same cell from being used twice in a single word path.' },
  { question: 'What happens when a DFS path fails to match the word?', options: ['The algorithm stops', 'The cell is permanently removed', 'The cell is unmarked and backtracking occurs', 'A new grid is created'], correctAnswer: 'The cell is unmarked and backtracking occurs', explanation: 'Backtracking restores the cell to its original character and tries the next direction.' },
  { question: 'What is the time complexity of Word Search where grid is m x n and word length is L?', options: ['O(m * n)', 'O(m * n * L)', 'O(m * n * 4^L)', 'O(4^L)'], correctAnswer: 'O(m * n * 4^L)', explanation: 'For each cell we may explore 4 directions at each of L levels, giving O(m * n * 4^L).' },
  { question: 'What is the space complexity of the Word Search algorithm?', options: ['O(1)', 'O(m * n)', 'O(L)', 'O(m * n * L)'], correctAnswer: 'O(L)', explanation: 'The recursion stack depth equals the length L of the word being searched.' },
  { question: 'What is the base case for the DFS recursion in Word Search?', options: ['Grid is empty', 'Index equals word length', 'Cell is out of bounds', 'Character does not match'], correctAnswer: 'Index equals word length', explanation: 'When the index reaches the word length, all characters have been matched — word is found.' },
  { question: 'Which data structure is implicitly used by the recursive DFS in Word Search?', options: ['Queue', 'Stack', 'Heap', 'Hash Map'], correctAnswer: 'Stack', explanation: 'Recursive DFS uses the call stack implicitly to track the current path.' },
  { question: 'Can the same cell be used more than once in a single word path?', options: ['Yes', 'No', 'Only for the first character', 'Only if the grid is large'], correctAnswer: 'No', explanation: 'Each cell can only be used once per path; it is marked visited during the current DFS call.' },
  { question: 'Word Search Grid is an example of which algorithm paradigm?', options: ['Greedy', 'Divide and Conquer', 'Dynamic Programming', 'Backtracking'], correctAnswer: 'Backtracking', explanation: 'Word Search systematically tries all paths and backtracks when a path does not lead to a solution.' },
];
