export const ratInMazeQuiz = [
  { question: 'What algorithmic paradigm is used to solve the Rat in a Maze problem?',options: ['Greedy Algorithm', 'Dynamic Programming', 'Backtracking', 'Divide and Conquer'],correctAnswer: 'Backtracking',explanation: 'Rat in a Maze uses backtracking to explore possible paths and undo invalid moves.'},
  { question: 'What is the main goal of the Rat in a Maze algorithm?',options: ['Find the shortest path', 'Find any valid path from source to destination', 'Count all paths', 'Sort the maze cells'],correctAnswer: 'Find any valid path from source to destination',explanation: 'The algorithm searches for a path from start to finish while avoiding blocked cells.'},
  { question: 'Which of the following is checked before moving to a next cell?',options: ['Cell is within bounds', 'Cell is not blocked', 'Cell is not already part of the current path', 'All of the above'],correctAnswer: 'All of the above',explanation: 'A move must stay within the maze, avoid obstacles, and not revisit the current path.'},
  { question: 'What happens when the algorithm reaches a dead end?',options: ['It terminates immediately', 'It backtracks to the previous cell', 'It marks the path as final', 'It ignores the dead end and continues'],correctAnswer: 'It backtracks to the previous cell',explanation: 'Backtracking removes the dead-end cell from the path and tries another direction.'},
  { question: 'What is typically used to mark a cell as part of the current path?',options: ['A visited array', 'A path matrix', 'A boolean flag', 'Any of the above'],correctAnswer: 'Any of the above',explanation: 'Different implementations use visited flags, path matrices, or other markers to avoid repeats.'},
  { question: 'What is the base case for a successful Rat in a Maze solution?', options: ['The rat reaches the destination cell', 'No moves are left', 'All cells are visited', 'The first move is valid'], correctAnswer: 'The rat reaches the destination cell',explanation: 'The algorithm succeeds when it reaches the destination following valid moves.'},
  { question: 'Which direction order can affect the found path but not correctness?',options: ['Only right and down', 'Up, down, left, right fixed order', 'Any fixed order of valid moves', 'Diagonal moves'],correctAnswer: 'Any fixed order of valid moves',explanation: 'The solver may use any consistent move order; the result path depends on that order.'},
  { question: 'What is the worst-case time complexity of Rat in a Maze on an N×N grid?',options: ['O(N)', 'O(N²)', 'O(2^(N×N))', 'O(log N)'],correctAnswer: 'O(2^(N×N))',explanation: 'Each cell may be visited or not in many combinations, leading to exponential worst-case time.'},
  { question: 'What does the algorithm return if no valid path exists?',options: ['True', 'False', 'The start cell', 'The full maze'],correctAnswer: 'False',explanation: 'If no path reaches the destination, the backtracking search fails and returns false.' },
  { question: 'Why is Rat in a Maze considered a good example of backtracking?',options: ['It uses greedy choices', 'It builds and unbuilds candidate paths', 'It sorts maze cells', 'It uses memoization'],correctAnswer: 'It builds and unbuilds candidate paths',explanation: 'Backtracking constructs paths step by step and removes them when they do not lead to a solution.' }
];