export const floydWarshallQuiz = [
    { question: 'What type of problem does the Floyd-Warshall algorithm solve?', options: ['Single-source shortest path', 'Minimum spanning tree', 'All-pairs shortest path', 'Topological sort'], correctAnswer: 'All-pairs shortest path', explanation: 'Floyd-Warshall finds the shortest paths between all pairs of vertices in a graph.' },
    { question: 'What is the time complexity of the Floyd-Warshall algorithm?', options: ['O(V²)', 'O(V³)', 'O(V*E)', 'O(V² log V)'], correctAnswer: 'O(V³)', explanation: 'The algorithm consists of three nested loops, each iterating over all V vertices, yielding O(V³) time.' },
    { question: 'What is the space complexity of Floyd-Warshall?', options: ['O(V)', 'O(V²)', 'O(E)', 'O(V*E)'], correctAnswer: 'O(V²)', explanation: 'We store distances in a 2D V x V matrix.' },
    { question: 'Under what condition does Floyd-Warshall fail or yield undefined results?', options: ['When there are negative edge weights', 'When there are negative-weight cycles', 'When the graph is disconnected', 'When the graph is unweighted'], correctAnswer: 'When there are negative-weight cycles', explanation: 'Negative-weight cycles allow paths to be infinitely small, causing the algorithm to fail to find a stable shortest path.' },
    { question: 'How can Floyd-Warshall detect a negative-weight cycle?', options: ['If dist[i][j] is negative', 'If dist[i][i] is negative for any vertex i', 'If any weight is negative', 'If the graph is directed'], correctAnswer: 'If dist[i][i] is negative for any vertex i', explanation: 'If a vertex has a path to itself with a negative cost (dist[i][i] < 0), a negative cycle exists.' },
    { question: 'Which paradigm does Floyd-Warshall use?', options: ['Greedy', 'Divide and conquer', 'Dynamic programming', 'Backtracking'], correctAnswer: 'Dynamic programming', explanation: 'It constructs solutions to larger paths using optimal solutions to smaller sub-paths.' },
    { question: 'What is the transition formula for Floyd-Warshall?', options: ['dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])', 'dist[i][j] = dist[i][k] * dist[k][j]', 'dist[i][j] = max(dist[i][j], dist[i][k])', 'dist[i][j] = dist[i-1][j-1]'], correctAnswer: 'dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])', explanation: 'We compare the current path i-j with the path through intermediate vertex k.' },
    { question: 'In the outer loop of Floyd-Warshall, what does the index variable represent?', options: ['The source vertex', 'The destination vertex', 'The intermediate vertex', 'The edge index'], correctAnswer: 'The intermediate vertex', explanation: 'The outer loop k represents the intermediate vertex we are allowing in the paths.' },
    { question: 'If a graph is extremely sparse (E << V²), which alternative is more efficient for all-pairs shortest paths?', options: ['Running Bellman-Ford V times', 'Running Dijkstras algorithm V times with priority queue', 'Running BFS V times', 'Prim algorithm'], correctAnswer: 'Running Dijkstras algorithm V times with priority queue', explanation: 'Dijkstra V times takes O(V*E log V), which is faster than O(V³) for sparse graphs.' },
    { question: 'What is the initial value of dist[i][j] if there is no direct edge between i and j?', options: ['0', '-1', 'Infinity', 'W'], correctAnswer: 'Infinity', explanation: 'No direct path means infinite distance initially.' }
  ];
