export const nQueensQuiz = [
  { question: 'What algorithmic technique is commonly used to solve the N-Queens problem?',options: ['Greedy Algorithm', 'Dynamic Programming', 'Backtracking', 'Divide and Conquer'],correctAnswer: 'Backtracking',explanation: 'N-Queens uses backtracking to place queens one by one and remove them when a conflict is found.'},
  { question: 'What is the main constraint for placing two queens on the board?',options: ['They cannot share the same row', 'They cannot share the same column', 'They cannot share the same diagonal', 'All of the above'],correctAnswer: 'All of the above',explanation: 'Queens must not attack each other, so they cannot share row, column, or diagonal.'},
  { question: 'What is the usual base case in a recursive N-Queens solver?',options: ['All queens are placed successfully', 'A queen is placed in the first row', 'Nothing is placed', 'All rows are empty'],correctAnswer: 'All queens are placed successfully',explanation: 'The recursion stops when the solver has placed queens on all rows without conflict.'},
  { question: 'How does the solver proceed after placing a queen in a row?',options: ['Place another queen in the same row', 'Move to the next row and try placements', 'Restart the board', 'Stop immediately'],correctAnswer: 'Move to the next row and try placements',explanation: 'The solver advances row by row, trying valid columns for each queen.'},
  { question: 'What happens when no valid column exists for a queen in the current row?',options: ['The solver declares no solution', 'The solver backtracks to the previous row', 'The solver skips the row', 'The solver moves diagonally'],correctAnswer: 'The solver backtracks to the previous row',explanation: 'If no column is valid, the algorithm backtracks and changes the previous queen placement.'},
  { question: 'Which data structure is often used to check column conflicts efficiently?',options: ['Array of columns', 'Stack of rows', 'Queue of diagonals', 'Hash of cells'],correctAnswer: 'Array of columns',explanation: 'An array of occupied columns helps quickly determine if a column is already used.'},
  { question: 'How many possible placements are there for the first queen on an N×N board?',options: ['1', 'N', 'N²', '2N'],correctAnswer: 'N',explanation: 'The first queen may be placed in any of the N columns in the first row.' },
  { question: 'Which of these is a valid check for a diagonal conflict?',options: ['row difference equals column difference', 'row sum equals column sum', 'row difference equals column sum', 'row sum equals column difference'],correctAnswer: 'row difference equals column difference',explanation: 'Queens conflict on the same diagonal when the absolute row difference equals the absolute column difference.'},
  { question: 'What is the space complexity of a typical recursive N-Queens solution on an N×N board?',options: ['O(1)', 'O(N)', 'O(N²)', 'O(2^N)'],correctAnswer: 'O(N)',explanation: 'The recursion stack and placement arrays grow linearly with N.'},
  { question: 'What is a common goal of an N-Queens solver?',options: ['Find one valid arrangement', 'Count all valid arrangements', 'Find the shortest path', 'Sort the board'],correctAnswer: 'Find one valid arrangement',explanation: 'Many implementations first aim to find at least one valid N-Queens configuration, though counting all solutions is also possible.'}
];