export const generateParenthesesQuiz = [
    { question: 'What algorithm technique is used to generate all valid parentheses?', options: ['Dynamic Programming', 'Greedy', 'Backtracking', 'Divide and Conquer'], correctAnswer: 'Backtracking', explanation: 'Backtracking is used to build combinations step by step and prune invalid paths.' },
    { question: 'For n = 3, how many valid parentheses combinations exist?', options: ['4', '5', '6', '8'], correctAnswer: '5', explanation: 'The number of valid combinations equals the nth Catalan number. For n=3, it is 5.' },
    { question: 'What is the condition to place an open bracket "("?', options: ['open > n', 'open == close', 'open < n', 'close < n'], correctAnswer: 'open < n', explanation: 'We can add "(" only if the number of open brackets used is less than n.' },
    { question: 'What is the condition to place a close bracket ")"?', options: ['close < n', 'close < open', 'close == open', 'open == n'], correctAnswer: 'close < open', explanation: 'We can add ")" only if close count is less than open count to maintain validity.' },
    { question: 'What is the length of each valid combination for n pairs?', options: ['n', 'n+1', '2n', '2n+1'], correctAnswer: '2n', explanation: 'Each valid combination has exactly n open and n close brackets, totalling 2n characters.' },
    { question: 'What is the time complexity of generating all valid parentheses?', options: ['O(n²)', 'O(2^n)', 'O(4^n / sqrt(n))', 'O(n log n)'], correctAnswer: 'O(4^n / sqrt(n))', explanation: 'The number of valid combinations is the nth Catalan number, bounded by O(4^n / sqrt(n)).' },
    { question: 'What is the space complexity of the recursive approach?', options: ['O(1)', 'O(n)', 'O(2n)', 'O(4^n)'], correctAnswer: 'O(n)', explanation: 'The recursion stack depth is at most 2n, which simplifies to O(n).' },
    { question: 'Which data structure is commonly used to store results in this problem?', options: ['Stack', 'Queue', 'List/Array', 'Hash Map'], correctAnswer: 'List/Array', explanation: 'All valid combinations are collected into a list/array as the base case is reached.' },
    { question: 'When do we add a combination to the result?', options: ['When open == n', 'When close == n', 'When the string length equals 2*n', 'When open == close'], correctAnswer: 'When the string length equals 2*n', explanation: 'A combination is complete and valid when its length reaches 2*n.' },
    { question: 'For n = 1, what is the only valid parentheses combination?', options: ['()', ')(', '((', '))'], correctAnswer: '()', explanation: 'For n=1, the only valid combination is "()" — one open and one close bracket.' },
];
