export const coinChangeQuiz = [
    { question: 'What is the output of Coin Change for coins [1, 2, 5] and amount 11?', options: ['2', '3', '4', '5'], correctAnswer: '3', explanation: 'Min coins = 5 + 5 + 1 (3 coins).' },
    { question: 'What does the DP state dp[i] represent in the Minimum Coins problem?', options: ['Number of combinations to make amount i', 'Minimum number of coins to make amount i', 'Maximum value of coins to make amount i', 'Whether amount i is prime'], correctAnswer: 'Minimum number of coins to make amount i', explanation: 'dp[i] stores the minimum number of coins needed to make amount i.' },
    { question: 'What is the time complexity of the Coin Change problem for amount A and n coin types?', options: ['O(n)', 'O(A)', 'O(A*n)', 'O(2^n)'], correctAnswer: 'O(A*n)', explanation: 'We iterate from 1 to A, and at each step we check all n coins.' },
    { question: 'What value should dp[i] be initialized to (except dp[0])?', options: ['0', 'amount + 1 (or Infinity)', '-1', '1'], correctAnswer: 'amount + 1 (or Infinity)', explanation: 'We initialize with a value greater than any possible answer (like amount+1) because we want to find the minimum.' },
    { question: 'Which transition formula is correct for Coin Change?', options: ['dp[i] = min(dp[i], dp[i-c] + 1)', 'dp[i] = dp[i-c]', 'dp[i] = max(dp[i], dp[i-c] + 1)', 'dp[i] = dp[i-1] + c'], correctAnswer: 'dp[i] = min(dp[i], dp[i-c] + 1)', explanation: 'To make amount i, we take the minimum of current dp[i] and 1 coin plus the min coins for remaining amount (i-c).' },
    { question: 'What is the space complexity of the standard DP solution for Coin Change?', options: ['O(1)', 'O(n)', 'O(A)', 'O(A*n)'], correctAnswer: 'O(A)', explanation: 'We only need a 1D array of size A+1 to store the computed results.' },
    { question: 'What should the function return if it is impossible to make the amount with the given coins?', options: ['0', 'Infinity', '-1', 'null'], correctAnswer: '-1', explanation: 'By convention (like LeetCode 322), we return -1 if the amount cannot be formed.' },
    { question: 'Can the Coin Change problem be solved greedily for any set of denominations?', options: ['Yes, always', 'No, only for canonical coin systems (e.g. US coins)', 'No, never', 'Yes, but it is slow'], correctAnswer: 'No, only for canonical coin systems (e.g. US coins)', explanation: 'A greedy approach works for systems like US currency, but fails for arbitrary systems (e.g., coins [1, 3, 4] for amount 6: greedy gives 4+1+1 (3 coins), DP gives 3+3 (2 coins)).' },
    { question: 'What is the value of dp[0]?', options: ['1', '0', '-1', 'Infinity'], correctAnswer: '0', explanation: 'Making amount 0 requires exactly 0 coins.' },
    { question: 'If we have coins [2] and amount 3, what is the output?', options: ['-1', '1', '2', '0'], correctAnswer: '-1', explanation: 'We cannot make amount 3 using only coins of value 2.' }
  ];
