export const AVLTreeQuiz = [
    { question: 'What does AVL stand for in AVL Tree?', options: ['Adelson-Velsky and Landis', 'Automatic Variable Length', 'Advanced Vector List', 'Adaptive Value Lookup'], correctAnswer: 'Adelson-Velsky and Landis', explanation: 'AVL Tree was invented by Georgy Adelson-Velsky and Evgenii Landis in 1962.' },
    { question: 'What is the balance factor of a node in an AVL tree?', options: ['height(left) + height(right)', 'height(right) - height(left)', 'height(left) - height(right)', 'height(left) * height(right)'], correctAnswer: 'height(left) - height(right)', explanation: 'Balance factor = height(left subtree) - height(right subtree). It must be -1, 0, or 1.' },
    { question: 'What is the allowed range of balance factor in an AVL tree?', options: ['-2 to 2', '0 to 1', '-1 to 1', '0 to 2'], correctAnswer: '-1 to 1', explanation: 'Every node in an AVL tree must have a balance factor of -1, 0, or 1 to maintain balance.' },
    { question: 'Which rotation is applied when a node is inserted into the right subtree of the right child?', options: ['Left-Left rotation', 'Right-Right rotation', 'Left-Right rotation', 'Right-Left rotation'], correctAnswer: 'Right-Right rotation', explanation: 'RR imbalance is fixed with a single left rotation on the unbalanced node.' },
    { question: 'What is the time complexity of insertion in an AVL tree?', options: ['O(n)', 'O(n log n)', 'O(log n)', 'O(1)'], correctAnswer: 'O(log n)', explanation: 'AVL trees maintain O(log n) height, so insertion takes O(log n) time.' },
    { question: 'What is the time complexity of search in an AVL tree?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], correctAnswer: 'O(log n)', explanation: 'Since AVL trees are balanced BSTs, search always takes O(log n) time.' },
    { question: 'Which rotation fixes a Left-Right (LR) imbalance?', options: ['Single right rotation', 'Single left rotation', 'Left rotation then right rotation', 'Right rotation then left rotation'], correctAnswer: 'Left rotation then right rotation', explanation: 'LR imbalance requires a left rotation on the left child followed by a right rotation on the unbalanced node.' },
    { question: 'How many rotations are needed to fix a Right-Left (RL) imbalance?', options: ['1', '2', '3', '0'], correctAnswer: '2', explanation: 'RL imbalance requires two rotations: first a right rotation on the right child, then a left rotation on the unbalanced node.' },
    { question: 'What is the maximum height of an AVL tree with n nodes?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(√n)'], correctAnswer: 'O(log n)', explanation: 'The height of an AVL tree is always O(log n), guaranteeing efficient operations.' },
    { question: 'What property does an AVL tree guarantee that a plain BST does not?', options: ['Unique keys', 'Sorted order', 'Height balance', 'Complete tree shape'], correctAnswer: 'Height balance', explanation: 'AVL trees self-balance after every insertion and deletion, ensuring O(log n) height at all times.' },
];
