export const medianOfTwoSortedArraysQuiz = [
    { question: 'What is the optimal time complexity to find the median of two sorted arrays of sizes m and n?', options: ['O(m+n)', 'O(log(m*n))', 'O(log(min(m, n)))', 'O(1)'], correctAnswer: 'O(log(min(m, n)))', explanation: 'By running binary search on the smaller array, we find the partition in O(log(min(m, n))).' },
    { question: 'Why do we perform binary search on the smaller array rather than the larger one?', options: ['To reduce binary search range and prevent out of bounds', 'Because the larger array cannot be searched', 'To save space', 'To sort them first'], correctAnswer: 'To reduce binary search range and prevent out of bounds', explanation: 'Searching the smaller array ensures that the calculated partition index in the larger array is always valid.' },
    { question: 'If total number of elements (m+n) is odd, how is the median determined after partitioning?', options: ['Average of two middle elements', 'Maximum of the left partition boundary elements', 'Minimum of the right partition boundary elements', 'The first element'], correctAnswer: 'Maximum of the left partition boundary elements', explanation: 'If odd, the left partition contains one extra element, which is the median (max of the left half).' },
    { question: 'If total number of elements (m+n) is even, how is the median determined?', options: ['Max of left half', 'Min of right half', 'Average of max of left half and min of right half', 'Average of first and last elements'], correctAnswer: 'Average of max of left half and min of right half', explanation: 'For even count, we average the largest element in the left half and the smallest in the right half.' },
    { question: 'If we partition nums1 at i and nums2 at j, what is the value of j in terms of i, m, and n?', options: ['j = (m + n) / 2 - i', 'j = (m + n + 1) / 2 - i', 'j = i + (m - n) / 2', 'j = (m + n) / 2 + i'], correctAnswer: 'j = (m + n + 1) / 2 - i', explanation: 'This formula balances the partitions such that left size = (m + n + 1) / 2.' },
    { question: 'What is the median of nums1 = [1, 3] and nums2 = [2]?', options: ['1.5', '2.0', '1.0', '3.0'], correctAnswer: '2.0', explanation: 'Merged sorted array is [1, 2, 3], the middle element is 2.0.' },
    { question: 'What is the space complexity of the optimal partition-based median algorithm?', options: ['O(m+n)', 'O(min(m, n))', 'O(1)', 'O(log(m+n))'], correctAnswer: 'O(1)', explanation: 'The partition method only uses constant extra variables.' },
    { question: 'If nums1[i-1] > nums2[j], what adjustment is made in the binary search?', options: ['Move search range left (high = i - 1)', 'Move search range right (low = i + 1)', 'Stop search', 'Swap arrays'], correctAnswer: 'Move search range left (high = i - 1)', explanation: 'If nums1[i-1] is too large, we must decrease the partition size in nums1, which means moving left.' },
    { question: 'What is the median of nums1 = [1, 2] and nums2 = [3, 4]?', options: ['2.0', '3.0', '2.5', '1.5'], correctAnswer: '2.5', explanation: 'Merged is [1, 2, 3, 4]. Median is (2 + 3) / 2.0 = 2.5.' },
    { question: 'Which method is the simplest but suboptimal (O(m+n) time) to find the median?', options: ['Two-pointer merging of sorted arrays', 'Binary search', 'Quickselect', 'Heap sorting'], correctAnswer: 'Two-pointer merging of sorted arrays', explanation: 'Merging the two arrays up to the middle element takes linear O(m+n) time.' }
  ];
