export const longestSubstringQuiz = [
    { question: 'What technique is used to solve Longest Substring Without Repeating Characters optimally?', options: ['Dynamic Programming', 'Sliding Window', 'Divide and Conquer', 'Backtracking'], correctAnswer: 'Sliding Window', explanation: 'The sliding window technique maintains a window of unique characters and expands/shrinks it efficiently.' },
    { question: 'What is the time complexity of the optimal sliding window solution?', options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'], correctAnswer: 'O(n)', explanation: 'Each character is visited at most twice — once by the right pointer and once by the left pointer.' },
    { question: 'What data structure is used to track characters in the current window?', options: ['Stack', 'Queue', 'Hash Map or Set', 'Array only'], correctAnswer: 'Hash Map or Set', explanation: 'A hash map stores the last seen index of each character, or a set tracks characters in the current window.' },
    { question: 'What happens when a duplicate character is found in the window?', options: ['Reset the entire window', 'Move the left pointer past the previous occurrence', 'Stop the algorithm', 'Skip the character'], correctAnswer: 'Move the left pointer past the previous occurrence', explanation: 'The left pointer jumps to one position after the last occurrence of the duplicate to remove it from the window.' },
    { question: 'What is the space complexity of the sliding window solution?', options: ['O(1)', 'O(n)', 'O(min(n, m))', 'O(n²)'], correctAnswer: 'O(min(n, m))', explanation: 'Space is used for the hash map/set which holds at most min(n, m) entries where m is the character set size.' },
    { question: 'For input "abcabcbb", what is the length of the longest substring without repeating characters?', options: ['2', '3', '4', '5'], correctAnswer: '3', explanation: 'The longest substring is "abc" with length 3.' },
    { question: 'For input "bbbbb", what is the answer?', options: ['5', '1', '0', '2'], correctAnswer: '1', explanation: 'All characters are the same, so the longest substring without repeating is just "b" with length 1.' },
    { question: 'For input "pwwkew", what is the answer?', options: ['2', '3', '4', '1'], correctAnswer: '3', explanation: 'The longest substring without repeating characters is "wke" with length 3.' },
    { question: 'What is the answer for an empty string ""?', options: ['0', '1', '-1', 'undefined'], correctAnswer: '0', explanation: 'An empty string has no characters, so the longest substring length is 0.' },
    { question: 'Which pointer expands the window in the sliding window approach?', options: ['Left pointer', 'Right pointer', 'Both pointers', 'Middle pointer'], correctAnswer: 'Right pointer', explanation: 'The right pointer moves forward to expand the window, while the left pointer shrinks it when duplicates are found.' },
];
