export const knapsackQuiz = [
    { question: 'What does the "0/1" in 0/1 Knapsack mean?', options: ['Fractional items are allowed', 'Items must either be fully taken or left behind', 'Items have binary values only', 'The capacity can only be 0 or 1'], correctAnswer: 'Items must either be fully taken or left behind', explanation: '0/1 means selection is binary (0 for skip, 1 for take).' },
    { question: 'What is the time complexity of the DP solution to 0/1 Knapsack for n items and capacity W?', options: ['O(2^n)', 'O(n*W)', 'O(n log n)', 'O(W log n)'], correctAnswer: 'O(n*W)', explanation: 'We fill a 2D table of size (n+1) x (W+1) which takes O(n*W) operations.' },
    { question: 'Under what condition does the DP approach for 0/1 Knapsack run in pseudo-polynomial time rather than polynomial time?', options: ['When weights are integers', 'When W depends on the input size exponentially', 'When there are duplicate weights', 'When values are float'], correctAnswer: 'When W depends on the input size exponentially', explanation: 'Since W is a numeric value, the time complexity depends on the value of W, which is exponential in terms of input bit length.' },
    { question: 'What is the DP state transition if weight of item i is greater than current capacity w?', options: ['dp[i][w] = dp[i-1][w]', 'dp[i][w] = val[i] + dp[i-1][w]', 'dp[i][w] = dp[i][w-1]', 'dp[i][w] = 0'], correctAnswer: 'dp[i][w] = dp[i-1][w]', explanation: 'If the item is heavier than capacity, we cannot pick it, so the max value remains the same as without it.' },
    { question: 'What is the space complexity of 0/1 Knapsack using a 1D array space-optimization?', options: ['O(n)', 'O(W)', 'O(n*W)', 'O(1)'], correctAnswer: 'O(W)', explanation: 'By iterating backwards, we only need a 1D array of size W+1.' },
    { question: 'How is the fractional knapsack problem typically solved?', options: ['Dynamic programming', 'Greedy algorithm', 'Divide and conquer', 'Backtracking'], correctAnswer: 'Greedy algorithm', explanation: 'Fractional knapsack can be solved optimally in O(n log n) by sorting items by value-to-weight ratio.' },
    { question: 'If item weights are [1, 2, 3] and values [10, 15, 40] with capacity 6, what is the max value?', options: ['40', '55', '65', '25'], correctAnswer: '65', explanation: 'Take all items: total weight 6, value 10+15+40=65.' },
    { question: 'In the 1D space-optimized version of 0/1 Knapsack, why do we iterate capacity backwards?', options: ['To process heavier items first', 'To prevent using the same item multiple times in the same step', 'To speed up computation', 'To sorted the array'], correctAnswer: 'To prevent using the same item multiple times in the same step', explanation: 'Iterating backwards ensures we refer to values from the previous item state, not the current one.' },
    { question: 'Can the 0/1 Knapsack be solved using Dijkstra?', options: ['No', 'Yes, as a shortest path tree', 'Yes, on a state space graph', 'Yes, only if weights are 1'], correctAnswer: 'Yes, on a state space graph', explanation: 'It is possible to model states (item index, weight) as nodes and find the longest path, but it is less efficient than standard DP.' },
    { question: 'What does dp[0][w] represent in the DP table?', options: ['The value with 0 capacity', 'The value when no items are considered', 'The value of the first item', 'The maximum possible value'], correctAnswer: 'The value when no items are considered', explanation: 'Row 0 represents the knapsack with 0 items, which has 0 value.' }
  ];
